//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCollage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDepartment
    {
        public int ID { get; set; }
        public int StudentFK { get; set; }
        public int DepartmnetFK { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Student Student { get; set; }
    }
}
